# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Tests

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Add .clasprc.json to home folder
        run: echo "$DOT_CLASPRC" > $HOME/.clasprc.json
        env:
          DOT_CLASPRC: ${{ secrets.DOT_CLASPRC }}
      - name: Add .clasp.json to project directory
        run: echo "$DOT_CLASP" > .clasp.json
        env:
          DOT_CLASP: ${{ secrets.DOT_CLASP }}
      - name: Add https certs
        run: mkdir certs && echo "$CERT_PEM" > ./certs/cert.pem && echo "$KEY_PEM" > ./certs/key.pem
        env:
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
      - name: Run integration tests
        run: npx cross-env EMAIL=$EMAIL PASSWORD=$PASSWORD npm run test:integration
        env:
          EMAIL: ${{ secrets.TEST_ACCOUNT_EMAIL }}
          PASSWORD: ${{ secrets.TEST_ACCOUNT_PASSWORD }}
